name: Release Android SDK

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version bump type"
        required: false
        default: "auto"
        type: choice
        options:
          - auto
          - patch
          - minor
          - major

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: "write"
  id-token: "write"
  pull-requests: "write"
  packages: "write"

jobs:
  version:
    name: Release Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.next }}
      from_tag: ${{ steps.semver.outputs.current }}
      to_tag: ${{ steps.semver.outputs.next }}
      changelog: ${{ steps.changelog.outputs.changes }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          branch: "main"
          token: ${{ github.token }}
          skipInvalidTags: true
          patchList: chore, fix, bugfix, perf, refactor, test, tests, ci
          maxTagsToFetch: 40
          majorList: ${{ github.event.inputs.version_type == 'major' && 'major' || '' }}
          minorList: ${{ github.event.inputs.version_type == 'minor' && 'minor' || '' }}
          patchAll: ${{ github.event.inputs.version_type == 'patch' && 'true' || 'false' }}

      - name: Update Package Version
        run: |
          NEXT_VERSION="${{ steps.semver.outputs.next }}"
          echo "Updating version to ${NEXT_VERSION}"

          # Update androidsdk/build.gradle.kts - android block version
          sed -i "s/version = \"v[0-9]*\.[0-9]*\.[0-9]*\"/version = \"${NEXT_VERSION}\"/" androidsdk/build.gradle.kts

          # Update androidsdk/build.gradle.kts - MavenPublication version
          sed -i "s/version = \"v[0-9]*\.[0-9]*\.[0-9]*\"/version = \"${NEXT_VERSION}\"/" androidsdk/build.gradle.kts

          # Update AccrueContextData.kt - sdkVersion
          sed -i "s/sdkVersion: String? = \"v[0-9]*\.[0-9]*\.[0-9]*\"/sdkVersion: String? = \"${NEXT_VERSION}\"/" androidsdk/src/main/java/com/accruesavings/androidsdk/AccrueContextData.kt

          # Commit changes
          git config --global user.name "Github Workflow"
          git config --global user.email "githubworkflow@accruemoney.com"
          git add -A
          git commit -m "build: updating package version to ${NEXT_VERSION} [skip ci]"
          git push origin main
          sleep 10

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Create github.properties
        run: |
          # Create github.properties if it doesn't exist or overwrite if it does
          echo "gpr.usr=${{ github.actor }}" > github.properties
          echo "gpr.key=${{ secrets.GITHUB_TOKEN }}" >> github.properties

      - name: Publish Package
        run: ./gradlew publish
        env:
          GPR_USER: ${{ github.actor }}
          GPR_API_KEY: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pre-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.semver.outputs.next }}
          generate_release_notes: true
          prerelease: true
          make_latest: false
          target_commitish: "main"

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ steps.semver.outputs.next }}
          toTag: ${{ steps.semver.outputs.current }}
          writeToFile: false
          includeRefIssues: false

  create-release:
    name: create-release
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.version.outputs.version }}
          body: ${{ needs.version.outputs.changelog }}
          prerelease: false
          make_latest: true
